# -*- coding: utf-8 -*-
"""ClassifierConstraint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5W48DyYUk3364M8e-Vy7xyYwzsKUfw0
"""

#!/usr/bin/env python
import os
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from transformers import RobertaTokenizer, RobertaModel

#############################################
# Hyperparameters and File Paths (edit as needed)
EPOCHS_PHASE1 = 5      # Number of epochs to train the two initial classifiers
EPOCHS_PHASE3 = 5         # Number of epochs to train the third classifier
BATCH_SIZE = 16           # Batch size
LEARNING_RATE = 2e-5      # Learning rate
MAX_LENGTH = 128          # Maximum token length for RoBERTa
NUM_CLASSES = 2           # Two classes: soft (0) and hard (1) constraint

# File paths (change these to your local paths)
LABELLED_FILE = r"app\data\Combined_Dataset_Constraint.csv"         # e.g., "./data/labelled.csv"
# LABELLED_FILE = "app/data/Combined_Dataset_Constraint.csv"          # for MacOS

UNLABELLED_FILE = r"app\data\Unlabelled_Constraint_Data.csv"        # e.g., "./data/unlabelled.csv"
# UNLABELLED_FILE = "app/data/Unlabelled_Constraint_Data.csv"         # for MacOS

# Model save path
MODEL_SAVE_PATH = r"app\Classifier Models\Constraints.pth"
# MODEL_SAVE_PATH = "app/Classifier Models/Constraints.pth"           # for MacOS

# Use Automatic Mixed Precision if using CUDA
USE_AMP = True
#############################################

# Enable benchmark for faster runtime if using GPU
if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True

# Custom Dataset for text (with or without labels)
class ConstraintDataset(Dataset):
    def __init__(self, texts, labels=None, tokenizer=None, max_length=128):
        self.texts = texts
        self.labels = labels  # For single-label classification, each label is an integer (0 or 1)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        inputs = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors="pt"
        )
        # Squeeze to remove the extra batch dimension
        input_ids = inputs["input_ids"].squeeze(0)
        attention_mask = inputs["attention_mask"].squeeze(0)
        if self.labels is not None:
            # Convert the label to a long tensor (for CrossEntropyLoss)
            label = torch.tensor(self.labels[idx], dtype=torch.long)
            return input_ids, attention_mask, label
        else:
            return input_ids, attention_mask

# Roberta-based classifier for single-label classification
class RobertaClassifier(nn.Module):
    def __init__(self, num_classes):
        super(RobertaClassifier, self).__init__()
        self.roberta = RobertaModel.from_pretrained('roberta-base')
        self.dropout = nn.Dropout(0.1)
        self.classifier = nn.Linear(self.roberta.config.hidden_size, num_classes)

    def forward(self, input_ids, attention_mask):
        outputs = self.roberta(input_ids=input_ids, attention_mask=attention_mask)
        # Use the representation of the first token (<s>) as the pooled output.
        pooled_output = outputs.last_hidden_state[:, 0]
        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)
        return logits

# Training function for one epoch with AMP (single-label version)
def train_epoch(model, data_loader, optimizer, device, criterion, use_amp):
    model.train()
    losses = []
    total_correct = 0
    total_examples = 0
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
    for batch in data_loader:
        input_ids, attention_mask, labels = [x.to(device) for x in batch]
        optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=use_amp):
            outputs = model(input_ids, attention_mask)  # shape: [batch_size, NUM_CLASSES]
            loss = criterion(outputs, labels)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        losses.append(loss.item())
        preds = torch.argmax(outputs, dim=1)
        total_correct += (preds == labels).sum().item()
        total_examples += labels.size(0)
    avg_acc = total_correct / total_examples
    return np.mean(losses), avg_acc

# Evaluation function (single-label version)
def eval_model(model, data_loader, device, criterion, use_amp):
    model.eval()
    losses = []
    total_correct = 0
    total_examples = 0
    with torch.no_grad():
        for batch in data_loader:
            input_ids, attention_mask, labels = [x.to(device) for x in batch]
            with torch.cuda.amp.autocast(enabled=use_amp):
                outputs = model(input_ids, attention_mask)
                loss = criterion(outputs, labels)
            losses.append(loss.item())
            preds = torch.argmax(outputs, dim=1)
            total_correct += (preds == labels).sum().item()
            total_examples += labels.size(0)
    avg_acc = total_correct / total_examples
    return np.mean(losses), avg_acc

# Function to predict labels (for pseudo-labeling) with AMP (single-label version)
def predict(model, data_loader, device, use_amp):
    model.eval()
    predictions = []
    with torch.no_grad():
        for batch in data_loader:
            # For unlabelled data, the batch has only (input_ids, attention_mask)
            if len(batch) == 3:
                input_ids, attention_mask, _ = [x.to(device) for x in batch]
            else:
                input_ids, attention_mask = [x.to(device) for x in batch]
            with torch.cuda.amp.autocast(enabled=use_amp):
                outputs = model(input_ids, attention_mask)
            preds = torch.argmax(outputs, dim=1)  # shape: [batch_size]
            predictions.extend(preds.cpu().numpy())
    return predictions

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
    pin_memory = True if device.type == "cuda" else False

    # ---- Data Loading ----
    # Load labelled data; assumes two columns: "Text" and "Constraint"
    df = pd.read_csv(LABELLED_FILE)
    # Convert 'Constraint' column to numeric, coercing errors to NaN
    df['Constraint'] = pd.to_numeric(df['Constraint'], errors='coerce')
    # Drop rows with NaN in 'Constraint' column
    df = df.dropna(subset=['Constraint'])
    texts = df["Text"].tolist()
    # Convert the constraint labels from 1/2 to 0/1
    labels = (df["Constraint"].astype(int) - 1).tolist()

    # Stratify using the labels
    X_temp, X_test, y_temp, y_test = train_test_split(
        texts, labels, test_size=0.1, random_state=42, stratify=labels
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_temp, y_temp, test_size=0.2222, random_state=42, stratify=y_temp
    )

    # Create PyTorch datasets and dataloaders for the labelled data
    train_dataset = ConstraintDataset(X_train, y_train, tokenizer, max_length=MAX_LENGTH)
    val_dataset = ConstraintDataset(X_val, y_val, tokenizer, max_length=MAX_LENGTH)
    test_dataset = ConstraintDataset(X_test, y_test, tokenizer, max_length=MAX_LENGTH)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, pin_memory=pin_memory)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, pin_memory=pin_memory)
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, pin_memory=pin_memory)

    # ---- Phase 1: Train Two Classifiers on Labelled Data ----
    print("\nPhase 1: Training two classifiers on labelled data")
    model1 = RobertaClassifier(NUM_CLASSES).to(device)
    model2 = RobertaClassifier(NUM_CLASSES).to(device)
    optimizer1 = optim.AdamW(model1.parameters(), lr=LEARNING_RATE)
    optimizer2 = optim.AdamW(model2.parameters(), lr=LEARNING_RATE)
    # Use CrossEntropyLoss for single-label classification
    criterion = nn.CrossEntropyLoss()

    for epoch in range(1, EPOCHS_PHASE1 + 1):
        train_loss1, train_acc1 = train_epoch(model1, train_loader, optimizer1, device, criterion, USE_AMP)
        val_loss1, val_acc1 = eval_model(model1, val_loader, device, criterion, USE_AMP)
        train_loss2, train_acc2 = train_epoch(model2, train_loader, optimizer2, device, criterion, USE_AMP)
        val_loss2, val_acc2 = eval_model(model2, val_loader, device, criterion, USE_AMP)

        print(f"\nEpoch {epoch}/{EPOCHS_PHASE1}")
        print(f"Model1 -> Train Loss: {train_loss1:.4f} | Train Acc: {train_acc1:.4f} || Val Loss: {val_loss1:.4f} | Val Acc: {val_acc1:.4f}")
        print(f"Model2 -> Train Loss: {train_loss2:.4f} | Train Acc: {train_acc2:.4f} || Val Loss: {val_loss2:.4f} | Val Acc: {val_acc2:.4f}")

    # ---- Phase 2: Pseudo-Label Unlabelled Data ----
    print("\nPhase 2: Labeling unlabelled data with the two classifiers")
    df_unlabelled = pd.read_csv(UNLABELLED_FILE)
    unlabelled_texts = df_unlabelled["Text"].tolist()
    unlabelled_dataset = ConstraintDataset(unlabelled_texts, labels=None, tokenizer=tokenizer, max_length=MAX_LENGTH)
    unlabelled_loader = DataLoader(unlabelled_dataset, batch_size=BATCH_SIZE, pin_memory=pin_memory)

    preds1 = predict(model1, unlabelled_loader, device, USE_AMP)
    preds2 = predict(model2, unlabelled_loader, device, USE_AMP)

    pseudo_texts = []
    pseudo_labels = []
    # Only add samples where both models agree on the predicted label
    for text, p1, p2 in zip(unlabelled_texts, preds1, preds2):
        if p1 == p2:
            pseudo_texts.append(text)
            pseudo_labels.append(p1)

    print(f"Pseudo-labelled {len(pseudo_texts)} out of {len(unlabelled_texts)} unlabelled samples (only where both models agree).")

    # ---- Phase 3: Train Third Classifier on Combined Data ----
    print("\nPhase 3: Training a third classifier on all (labelled + pseudo-labelled) data")
    # Combine the original training data with pseudo-labelled data
    combined_texts = X_train + pseudo_texts
    combined_labels = y_train + pseudo_labels

    combined_dataset = ConstraintDataset(combined_texts, combined_labels, tokenizer, max_length=MAX_LENGTH)
    combined_loader = DataLoader(combined_dataset, batch_size=BATCH_SIZE, shuffle=True, pin_memory=pin_memory)

    model3 = RobertaClassifier(NUM_CLASSES).to(device)
    optimizer3 = optim.AdamW(model3.parameters(), lr=LEARNING_RATE)

    for epoch in range(1, EPOCHS_PHASE3 + 1):
        train_loss, train_acc = train_epoch(model3, combined_loader, optimizer3, device, criterion, USE_AMP)
        val_loss, val_acc = eval_model(model3, val_loader, device, criterion, USE_AMP)
        print(f"\nEpoch {epoch}/{EPOCHS_PHASE3}")
        print(f"Model3 -> Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} || Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")

    # Optionally, save the final model weights
    torch.save(model3.state_dict(), MODEL_SAVE_PATH)
    print(f"\nModel weights saved to {MODEL_SAVE_PATH}")

if __name__ == "__main__":
    main()
